### ISSUE TITLE
Possible brace expansion issue

### ISSUE THREAD

**Issue by shannonmoeller** [jonschlinkert/look-up#3]
I was setting up some local benchmark tests and ran into a possible issue with brace expansion. Can you verify whether or not I correctly set the `look-up` options (right-hand middle)?

![screenshot 2015-05-05 14 02 18](https://cloud.githubusercontent.com/assets/155164/7479468/d4dde4d2-f32f-11e4-88f1-60e208d232ff.png)

**Comment by jonschlinkert** [comment]
I think you would need to either pass `matchBase` on the options, or use a globstar `**`. e.g.

```js
**/.{,config/}waldo
```

**Comment by jonschlinkert** [comment]
let me know if neither of those work. if not, we have a bug

**Comment by shannonmoeller** [comment]
I am currently passing matchBase. I'll give `**/` a try. Full source available in the [develop branch of `find-config`](https://github.com/shannonmoeller/find-config/blob/develop/test/look-up.bench.js).

**Comment by shannonmoeller** [comment]
Still no dice after adding `**/`.

**Comment by jonschlinkert** [comment]
oh, wait. that's a dotfile pattern. try passing `dot: true`

**Comment by jonschlinkert** [comment]
and maybe some combination of those other options. since it's also matching on an absolute path

**Comment by shannonmoeller** [comment]
Unfortunately still getting `null`. I know that the target file exists because the `findup-sync` and `find-config` tests are written exactly the same way and are in the same folder.

```js
var lookup = require('look-up'),
    path = require('path'),
    options = {
        cwd: path.join(__dirname, 'fixtures/a/b'),
        unixify: true,
        dot: true,
        nodupes: true,
        matchBase: true,
        braces: true,
        brackets: true,
        extglob: true,
        nonull: true,
        cache: true
    };

console.log(lookup('.{,config/}waldo', options));
console.log(lookup('**/.{,config/}waldo', options));
```

**Comment by jonschlinkert** [comment]
hmm, I'll need to look into it. I doubt it's brace expansion. it's possible, but I've used this pattern lot's of times. it's more likely a bug here. 
thanks for reporting

**Comment by jonschlinkert** [comment]
wait, try one more thing. don't pass any other options besides `dot: true`.

**Comment by jonschlinkert** [comment]
and `cwd`, sorry

**Comment by shannonmoeller** [comment]
Still `null`, sorry to say.

```js
var lookup = require('look-up'),
    path = require('path'),
    options = {
        cwd: path.join(__dirname, 'fixtures/a/b'),
        dot: true
    };

console.log(lookup('.{,config/}waldo', options));
console.log(lookup('**/.{,config/}waldo', options));
```

**Comment by jonschlinkert** [comment]
k. thanks for checking. I'll look into it

**Comment by shannonmoeller** [comment]
This works:

```js
var lookup = require('look-up'),
    path = require('path'),
    options = {
        cwd: path.join(__dirname, 'fixtures/a/b'),
        dot: true
    };

function test() {
    return lookup(['.waldo', '.config/waldo'], options);
}

console.log(test());
```

**Comment by shannonmoeller** [comment]
I've narrowed this down. It's a tree walking issue, not a brace expansion issue. There is only one path to drill down into the test fixtures (`a/b/c/d/e/f/g/h/i/j/`). So, when looking for `**/c/package.json` from `j/`, it will be found by the readdir calls and match the glob pattern because `c/` is an ancestor of `j/`, and `package.json` is a child of `c/`. So far so good.

However, if you fork the directory tree, we find the issue. Consider this structure where `d/` and `k/` are siblings:

```
a/ - b/ - c/ - d/ - e/ - f/ - g/ - h/ - i/ - j/
            `- k/ - l/ - package.json
```

When looking for `**/c/k/l/package.json` from `j/`, nothing will be found because the loop never calls `readdir` on the contents of `k/` and below. This is what's happening in the case of `.{,config/}waldo`. Because I'm looking into `.config/` which is not an ancestor of the starting cwd, `waldo` is never found because `readdir` is never called on `.config/`.

I'm not sure what the fix is, but would you be open to a PR to add a couple fixtures and a failing test?

**Comment by jonschlinkert** [comment]
> would you be open to a PR that adds a couple fixtures and a failing test?

of course, that would be great, thanks! I think I know how to solve, let me think about it I'll try to get a fix pushed up soon

**Comment by jonschlinkert** [comment]
closing since this lib was deprecated in favor of findup-sync
